version: "3.8"
networks:
  private:
    ipam:
      config:
        - subnet: 192.168.2.0/24 # 192.168.2.1 > 192.168.2.254
  public:
    ipam:
      config:
        - subnet: 192.168.3.0/24 # 192.168.3.1 > 192.168.3.254
volumes:
  gitea-db:
  gitea-data:
  credentials:
  jenkins_home:

services:
  traefik:
    restart: always
    container_name: traefik.workflow.com
    image: traefik:latest
    command:
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --api.insecure=true
      - --providers.docker
      - --accesslog=true
    ports:
      - 80:80
      - 443:443
    networks:
      public:
        ipv4_address: 192.168.3.254
      private:
        ipv4_address: 192.168.2.254

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.workflow.com`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.network-internet.ipwhitelist.sourcerange=0.0.0.0/0
      - traefik.http.middlewares.network-internal.ipwhitelist.sourcerange=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
      - traefik.http.middlewares.network-public.ipwhitelist.sourcerange=192.168.3.0/24
      - traefik.http.middlewares.network-private.ipwhitelist.sourcerange=192.168.2.0/24

  # whoami:
  #   restart: always
  #   image: traefik/whoami:latest
  #   container_name: whoami.workflow.com
  #   networks:
  #     public:
  #   labels:
  #     - traefik.http.routers.whoami.rule=Host(`whoami.workflow.com`)
  #     - traefik.http.routers.whoami.middlewares=network-internet@docker

  # whoami2:
  #   restart: always
  #   image: traefik/whoami:latest
  #   container_name: whoami2.workflow.com
  #   networks:
  #     private:
  #   labels:
  #     - traefik.http.routers.whoami2.rule=Host(`whoami2.workflow.com`)
  #     - traefik.http.routers.whoami2.middlewares=network-private@docker

  gitea-db:
      restart: always
      image: postgres:alpine
      container_name: db.gitea.workflow.com
      networks:
        private:
      volumes:
        - gitea-db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=gitea
        - POSTGRES_USER=gitea
        - POSTGRES_PASSWORD=gitea
      labels:
      - traefik.http.routers.gitea-db.rule=Host(`gitea-db.workflow.com`)
      - traefik.http.routers.gitea-db.middlewares=network-private@docker
      - traefik.http.services.gitea-db.loadbalancer.server.port=5432

  gitea:
      restart: always
      image: gitea/gitea:latest
      container_name: gitea.workflow.com
      networks:
        public:
        private:
      ports:
        - 2222:2222
      volumes:
        - gitea-data:/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      environment:
        - GITEA___APP_NAME=workflow.com
        - GITEA__picture__DISABLE_GRAVATAR=true
        - GITEA__openid__ENABLE_OPENID_SIGNIN=FALSE
        - GITEA__database__DB_TYPE=postgres
        - GITEA__database__HOST=db.gitea.workflow.com
        - GITEA__database__NAME=gitea
        - GITEA__database__USER=gitea
        - GITEA__database__PASSWD=gitea
        - GITEA__server__PROTOCOL=http
        - GITEA__server__DOMAIN=gitea.workflow.com
        - GITEA__server__ROOT_URL=%(PROTOCOL)s://%(DOMAIN)s/
        - GITEA__server__START_SSH_SERVER=true
        - GITEA__server__SSH_PORT=2222
        - GITEA__server__SSH_LISTEN_PORT=2222
        - GITEA__server__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
        - GITEA__server__DEFAULT_ENABLE_TIMETRACKING=false
        - GITEA__server__REQUIRE_SIGNIN_VIEW=false
        - GITEA__server__DESABLE_REGISTRATION=true
        - GITEA__server__ALLOWED_HOST_LIST=*
      labels:
      - traefik.http.routers.gitea.rule=Host(`gitea.workflow.com`)
      - traefik.http.routers.gitea.middlewares=network-internet@docker
      - traefik.http.services.gitea.loadbalancer.server.port=3000

  jenkins:
    user: root
    restart: always
    image: jenkins/jenkins:latest
    container_name: jenkins.workflow.com
    networks:
      public:
      private:
      #ports:
        #- 50000:50000
    volumes:
      - credentials:/credentials
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro #ro (read only)
      - /usr/bin/docker:/usr/bin/docker # ici on enleve ro, pour ne pas avoir de probleme avec lecture & ecriture
      - /usr/libexec:/usr/libexec
    labels:
      - traefik.http.routers.jenkins.rule=Host(`jenkins.workflow.com`)
      - traefik.http.routers.jenkins.middlewares=network-internet@docker
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
      #- traefik.http.services.jenkins.loadbalancer.server.port=50000